// Official Allay House catalogue — source data for
// backend/src/scripts/importOfficialCatalogue.js
//
// Kept separate from the import script so the catalogue content can be
// reviewed and edited without touching the transaction/safety logic.
//
// Field notes:
// - categorySlug must match an existing service_categories.slug (the 10
//   pre-existing categories, or the 2 new ones created in migration 009:
//   'waxing' and 'signature-experiences').
// - price is always the base/display price in naira (major units, matches
//   the existing services.price NUMERIC(12,2) column — never minor units).
// - priceFrom/priceTo are only set for ranged or "from" pricing.
// - short is the card description (1-2 sentences), description is the
//   detailed copy (2-4 sentences).
// - The "Allay Spa" category named in some spec revisions does not exist in
//   this database — the real, existing equivalent category is "Body & Beauty"
//   (slug: body-beauty), confirmed directly against the schema. Soft-sculpt/
//   contouring services are mapped there rather than creating a duplicate
//   category for a name that was never actually seeded.

export const legacySeededServiceSlugs = [
  'signature-glow-facial',
  'hydrating-facial',
  'deep-tissue-massage',
  'sauna-session',
  'headspa-ritual',
  'pilates-class',
  'brow-shaping-tint',
  'lash-lift-tint',
  'hair-styling',
  'braiding',
  'premium-human-hair-wig-consultation',
  'nail-care-session',
  'body-scrub-polish',
]

export const newCategories = [
  { name: 'Waxing', slug: 'waxing', description: 'Precise waxing services from brow to full body.', displayOrder: 11 },
  { name: 'Signature Experiences', slug: 'signature-experiences', description: 'Full-day, bridal and corporate wellness experiences at Allay House.', displayOrder: 12 },
]

function svc(fields) {
  return {
    priceFrom: null,
    priceTo: null,
    priceIsFrom: false,
    priceUnitLabel: null,
    serviceType: null,
    isAddon: false,
    isCouples: false,
    sessionCount: null,
    ...fields,
  }
}

export const officialServices = [
  // A. Scalp and head-spa services — category: headspa
  svc({ name: 'Express Head Spa', categorySlug: 'headspa', price: 45000, duration: 30, order: 1,
    short: 'A brisk scalp cleanse and massage for when time is short but your scalp still needs care.',
    description: 'A focused reset for the scalp, combining a gentle cleanse with a brief massage to ease tension and lift product build-up. Ideal between longer head-spa visits or as a quick pause in a busy week.' }),
  svc({ name: 'Signature Japanese Head Spa', categorySlug: 'headspa', price: 70000, duration: 60, order: 2,
    short: 'Our full Japanese-inspired scalp ritual, layering cleanse, steam and slow massage into one hour of calm.',
    description: 'Rooted in Japanese head-spa tradition, this hour moves through a deep cleanse, warm steam and an unhurried scalp massage designed to release tension and support a healthier-feeling scalp. It closes with a wash and gentle blow-dry, leaving hair light and scalp visibly refreshed.' }),
  svc({ name: 'Deluxe Head Spa + Steam + Shoulder Massage', categorySlug: 'headspa', price: 105000, duration: 90, order: 3,
    short: 'Our signature head spa extended with steam therapy and a shoulder massage for a fuller reset.',
    description: 'Ninety minutes built around the Signature Japanese Head Spa, extended with warm steam to open the senses and a shoulder massage that carries the calm beyond the scalp. A considered choice when you want the full ritual, unrushed.' }),
  svc({ name: 'Head Spa + Facial Combo', categorySlug: 'headspa', price: 140000, duration: 120, order: 4,
    short: 'A scalp and skin reset in one visit, pairing our head spa with a facial ritual.',
    description: 'Two of our most-loved rituals in a single appointment: a restorative head-spa treatment paired with a facial suited to your skin. A considered pairing for anyone wanting scalp and skin refreshed in one sitting.' }),
  svc({ name: 'Couples Head Spa Experience', categorySlug: 'headspa', price: 215000, duration: 90, order: 5, isCouples: true,
    short: 'Our signature head spa, side by side, for two.',
    description: 'Share the Signature Japanese Head Spa ritual with someone else in a shared session, cleanse, steam and massage included. A gentle, low-key way to unwind together.' }),
  svc({ name: 'Scalp Analysis', categorySlug: 'headspa', price: 15000, duration: 20, order: 6, isAddon: true,
    short: 'A closer look at your scalp’s condition to guide the right head-spa routine.',
    description: 'A guided scalp assessment that helps identify dryness, build-up or sensitivity, so your head-spa treatments can be tailored more precisely over time. Best added to a first visit or after a change in hair routine.' }),
  svc({ name: 'Hair Growth Treatment', categorySlug: 'headspa', price: 14000, duration: 30, order: 7, isAddon: true,
    short: 'A scalp-nourishing add-on formulated to support a healthier growth environment.',
    description: 'Added to any head-spa service, this treatment works the scalp with a nourishing formula intended to support circulation and a healthier-feeling foundation for hair growth over time.' }),
  svc({ name: 'Deep Hydration Treatment', categorySlug: 'headspa', price: 20000, duration: 30, order: 8, isAddon: true,
    short: 'An extra layer of moisture for scalp and hair that need it most.',
    description: 'A concentrated hydration step added to your head-spa visit, helping replenish scalp and strands that feel dry, tight or over-processed.' }),
  svc({ name: 'LED Scalp Therapy', categorySlug: 'headspa', price: 18000, duration: 25, order: 9, isAddon: true,
    short: 'Gentle LED light therapy layered onto your scalp treatment.',
    description: 'A calm, non-invasive LED light session added to any head-spa service, designed to complement your existing scalp-care routine. Offered as a wellness add-on rather than a medical treatment.' }),
  svc({ name: 'Extended Massage Time', categorySlug: 'headspa', price: 15000, duration: 15, order: 10, isAddon: true,
    short: 'A few more unhurried minutes of scalp and shoulder massage.',
    description: 'Add extra time to the massage portion of any head-spa service, for days when you would simply like to stay a little longer.' }),

  // B. Hair lounge — category: allay-salon
  svc({ name: 'Wash & Blowdry', categorySlug: 'allay-salon', price: 15000, duration: 45, order: 1,
    short: 'A thorough cleanse and smooth blow-dry finish.',
    description: 'A clean wash followed by a polished blow-dry, leaving hair smooth, light and ready for the day.' }),
  svc({ name: 'Wash & Style', categorySlug: 'allay-salon', price: 18000, duration: 60, order: 2,
    short: 'Wash, condition and styled finish, tailored to how you like to wear your hair.',
    description: 'A cleanse and condition followed by a styled finish suited to your hair type and the look you have in mind, from soft waves to a sleek set.' }),
  svc({ name: 'Wig Styling', categorySlug: 'allay-salon', price: 10000, duration: 45, order: 3,
    short: 'Styling for your own wig, brought in ready to wear.',
    description: 'Bring your own wig in for a fresh style, part and finish, refreshed to sit naturally and look newly done.' }),
  svc({ name: 'Cornrows', categorySlug: 'allay-salon', price: 15000, priceFrom: 15000, priceIsFrom: true, duration: 90, order: 4,
    short: 'Clean, close cornrow styling, priced from ₦15,000 depending on pattern and length.',
    description: 'Neatly parted cornrows in the pattern of your choice, sized to fit your styling plans whether worn alone or as a base for a wig or braid-out. Final price depends on pattern complexity, length and hair density.' }),

  // C. Knotless braids without extensions — category: hair-wigs
  svc({ name: 'Knotless Braids Without Extensions', categorySlug: 'hair-wigs', price: 70000, duration: 180, order: 1,
    short: 'Tension-free knotless braids at our standard length, no extensions added.',
    description: 'Our base knotless braid install, worked section by section with the same tension-free start as our longer lengths. A comfortable, natural-looking protective style using only your own hair.' }),
  svc({ name: 'Knotless Braids - Shoulder Length', categorySlug: 'hair-wigs', price: 90000, duration: 240, order: 2,
    short: 'Soft, tension-free knotless braids finished at shoulder length.',
    description: 'Knotless braiding worked in sections for a lighter, more comfortable install than traditional braids, finished at a manageable shoulder length. A protective style built to last while staying gentle on the hairline.' }),
  svc({ name: 'Knotless Braids - Mid Back Length', categorySlug: 'hair-wigs', price: 110000, duration: 300, order: 3,
    short: 'Knotless braids taken down to mid-back length for a fuller, longer finish.',
    description: 'The same tension-free knotless technique carried further, giving a longer, more dramatic finish that still starts light at the root.' }),
  svc({ name: 'Knotless Braids - Long Length', categorySlug: 'hair-wigs', price: 130000, duration: 360, order: 4,
    short: 'Knotless braids in a long, statement length.',
    description: 'A longer knotless install for anyone wanting real length and movement, braided section by section to keep the root comfortable throughout wear.' }),
  svc({ name: 'Knotless Braids - Extra Long Length', categorySlug: 'hair-wigs', price: 130000, duration: 420, order: 5,
    short: 'Our longest knotless braid length, for maximum length and drama.',
    description: 'The fullest length we offer in knotless braiding, built with the same tension-free start for comfort even at extra length and added wear time.' }),

  // D. Micro braids without extensions — category: hair-wigs
  svc({ name: 'Micro Braids - Shoulder Length', categorySlug: 'hair-wigs', price: 85000, duration: 300, order: 6,
    short: 'Fine, detailed micro braids finished at shoulder length.',
    description: 'Small, closely worked micro braids for a delicate, natural-looking finish, ending at shoulder length. A longer sitting reflecting the fine detail of the technique.' }),
  svc({ name: 'Micro Braids - Mid Back Length', categorySlug: 'hair-wigs', price: 105000, duration: 360, order: 7,
    short: 'Micro braids carried down to mid-back for extra length and flow.',
    description: 'The same fine micro-braiding technique extended to mid-back length, giving softer movement and a longer-lasting protective style.' }),
  svc({ name: 'Micro Braids - Long Length', categorySlug: 'hair-wigs', price: 125000, duration: 420, order: 8,
    short: 'Long, finely detailed micro braids.',
    description: 'Micro braids worked to a long, flowing finish, built section by section for a neat, natural-looking result that holds its shape well.' }),
  svc({ name: 'Micro Braids - Extra Long Length', categorySlug: 'hair-wigs', price: 145000, duration: 480, order: 9,
    short: 'Our longest micro braid length, for a dramatic, detailed finish.',
    description: 'The fullest micro-braid length we offer, reflecting the additional time and precision needed to carry fine braids to extra length.' }),

  // E. Wig services — category: hair-wigs
  svc({ name: 'Seamless Wig Install', categorySlug: 'hair-wigs', price: 45000, priceFrom: 45000, priceTo: 80000, duration: 120, order: 10,
    short: 'A natural, seamless wig install, from ₦45,000 to ₦80,000 depending on method and hair.',
    description: 'A melted, seamless wig install customised to your hairline and preferred method, from lace tinting to a natural parting. Final pricing depends on the wig type and install technique chosen at consultation.' }),
  svc({ name: 'Wig Refresh', categorySlug: 'hair-wigs', price: 20000, duration: 90, order: 11,
    short: 'A quick refresh to bring a worn wig back to life.',
    description: 'Cleaning, restyling and a light detangle for a wig that has lost its shine, leaving it ready to wear again.' }),
  svc({ name: 'Custom Wig Coloring', categorySlug: 'hair-wigs', price: 195000, priceFrom: 195000, priceIsFrom: true, duration: 240, order: 12,
    short: 'Bespoke wig colouring, from ₦195,000 depending on the shade and technique.',
    description: 'A custom colour service for your wig, from a full-tone change to dimensional highlights, worked to match the look you bring to consultation. Pricing depends on the depth of colour change and finishing time required.' }),

  // F. Hair treatments — category: hair-wigs
  svc({ name: 'Deep Moisture Treatment', categorySlug: 'hair-wigs', price: 20000, duration: 45, order: 13,
    short: 'A rich moisture treatment for hair that feels dry or brittle.',
    description: 'A concentrated moisture mask worked through the hair to help restore softness and manageability, finished with a light rinse and style.' }),
  svc({ name: 'Protein Treatment', categorySlug: 'hair-wigs', price: 25000, duration: 45, order: 14,
    short: 'A strengthening treatment for hair that needs extra resilience.',
    description: 'A protein-focused treatment designed to help reinforce strand structure, suited to hair that feels weak, over-processed or prone to breakage.' }),
  svc({ name: 'Bond Repair Treatment', categorySlug: 'hair-wigs', price: 30000, duration: 60, order: 15,
    short: 'An intensive bond-repair treatment for compromised, chemically treated hair.',
    description: 'A targeted treatment formulated to help rebuild internal hair bonds after colour, chemical or heat damage, leaving hair feeling stronger and smoother to the touch.' }),
  svc({ name: 'Scalp Detox Treatment', categorySlug: 'hair-wigs', price: 18000, duration: 45, order: 16,
    short: 'A cleansing treatment to lift build-up and refresh the scalp.',
    description: 'A deep-cleansing scalp treatment that clears product build-up and impurities, leaving the scalp feeling lighter ahead of your next style.' }),

  // G. Body massage rituals — category: massage
  svc({ name: 'Swedish Massage', categorySlug: 'massage', price: 65000, duration: 60, order: 1,
    short: 'A classic full-body massage with long, flowing strokes for total relaxation.',
    description: 'Long, rhythmic strokes worked across the full body to ease everyday tension and encourage deep relaxation. A gentle, restorative choice for first-time and regular guests alike.' }),
  svc({ name: 'Deep Tissue Massage', categorySlug: 'massage', price: 75000, duration: 75, order: 2,
    short: 'Firmer, targeted pressure for persistent tightness and tension.',
    description: 'Slower, more deliberate pressure worked into areas of chronic tightness, ideal after intense activity or long stretches of desk-bound tension.' }),
  svc({ name: 'Aromatherapy Massage', categorySlug: 'massage', price: 80000, duration: 75, order: 3,
    short: 'A full-body massage layered with essential oils chosen to suit your mood.',
    description: 'A soothing full-body massage paired with essential oils selected for you, combining touch and scent for a more complete sense of calm.' }),
  svc({ name: 'Hot Stone Massage', categorySlug: 'massage', price: 90000, duration: 75, order: 4,
    short: 'Warmed stones and flowing strokes work together to melt away tension.',
    description: 'Smooth, heated stones are worked alongside traditional massage strokes to help ease deep tension and encourage full-body relaxation.' }),
  svc({ name: 'Stress Relief Back Massage', categorySlug: 'massage', price: 45000, duration: 45, order: 5,
    short: 'A focused back massage for a quick, meaningful reset.',
    description: 'A shorter session concentrated on the back, neck and shoulders, the areas that carry the most everyday tension, for a quick but meaningful reset.' }),

  // H. Premium massage experiences — category: massage
  svc({ name: 'Full Body Candle Massage', categorySlug: 'massage', price: 95000, duration: 75, order: 6, serviceType: 'premium',
    short: 'A warm-oil massage using a melted massage candle for deep, silky relaxation.',
    description: 'A full-body massage using warm oil from a melted massage candle, glide and warmth combined for a deeply relaxing, sensory experience.' }),
  svc({ name: 'Four Hands Massage', categorySlug: 'massage', price: 135000, duration: 75, order: 7, serviceType: 'premium',
    short: 'Two therapists working in synchronised rhythm for a fuller sense of release.',
    description: 'Two therapists work in tandem across the body, mirroring each other’s movements for a more immersive and complete massage experience.' }),
  svc({ name: 'Couples Massage', categorySlug: 'massage', price: 165000, duration: 75, order: 8, isCouples: true, serviceType: 'premium',
    short: 'A side-by-side massage experience for two.',
    description: 'Share a full-body massage together in the same room, each guided by your own therapist, for a shared moment of calm.' }),
  svc({ name: 'Hot Stone Massage for Two', categorySlug: 'massage', price: 140000, duration: 75, order: 9, isCouples: true, serviceType: 'premium',
    short: 'Our hot stone massage, shared side by side.',
    description: 'The warmth and release of our Hot Stone Massage, experienced together in a shared session designed for two.' }),

  // I. Body glow and hammam rituals — category: sauna
  svc({ name: 'Traditional Hammam', categorySlug: 'sauna', price: 70000, duration: 60, order: 1,
    short: 'A classic steam and exfoliation ritual rooted in hammam tradition.',
    description: 'Warm steam opens the skin ahead of a full-body exfoliation, following the traditional hammam sequence for a deep, thorough cleanse and softer skin.' }),
  svc({ name: 'Deluxe Moroccan Hammam', categorySlug: 'sauna', price: 120000, duration: 90, order: 2,
    short: 'An elevated hammam ritual with black soap, steam and a rinse-down finish.',
    description: 'A fuller Moroccan hammam sequence, steam, black soap cleanse, exfoliation and a rinse-down finish, for skin that feels noticeably smoother and refreshed.' }),
  svc({ name: 'Hammam + Massage Package', categorySlug: 'sauna', price: 160000, duration: 150, order: 3, serviceType: 'package',
    short: 'Our hammam ritual paired with a full massage for a longer, fuller reset.',
    description: 'The Deluxe Moroccan Hammam paired with a full-body massage in one extended visit, cleansing and relaxation combined.' }),
  svc({ name: 'Extra Brightening Hammam for Two', categorySlug: 'sauna', price: 150000, duration: 90, order: 4, isCouples: true,
    short: 'A brightening hammam ritual shared side by side, for two.',
    description: 'Our brightening hammam sequence experienced together, steam, cleanse and exfoliation shared in the same session for two.' }),
  svc({ name: 'Coffee Body Scrub', categorySlug: 'sauna', price: 55000, duration: 45, order: 5,
    short: 'An invigorating coffee-based scrub for smoother, brighter-feeling skin.',
    description: 'A full-body exfoliation using a coffee-based scrub, buffing away rough, dry patches and leaving skin feeling noticeably smoother.' }),
  svc({ name: 'Glow Body Polish', categorySlug: 'sauna', price: 60000, duration: 45, order: 6,
    short: 'A smoothing full-body polish finished with hydrating lotion.',
    description: 'A gentle full-body exfoliation followed by a hydrating lotion application, leaving skin soft, even and glowing.' }),
  svc({ name: 'Detox Body Wrap', categorySlug: 'sauna', price: 75000, duration: 60, order: 7,
    short: 'A warming body wrap designed to leave skin feeling refreshed and toned.',
    description: 'A mineral-rich body wrap applied and left to work while you rest, intended to leave the skin feeling refreshed, smoother and lightly toned.' }),
  svc({ name: 'Brightening Body Treatment', categorySlug: 'sauna', price: 90000, duration: 75, order: 8,
    short: 'A full-body treatment focused on an even, brighter-looking skin tone.',
    description: 'A layered treatment combining exfoliation and brightening actives worked across the full body, for skin that looks and feels more even in tone.' }),

  // J. Soft sculpt body treatments — category: body-beauty (the real, existing
  // category some spec revisions call "Allay Spa" — see file header note).
  svc({ name: 'Lymphatic Drainage', categorySlug: 'body-beauty', price: 48000, duration: 30, order: 1,
    short: 'A gentle, rhythmic massage technique designed to support lymphatic flow.',
    description: 'A light, targeted massage using rhythmic strokes intended to support natural lymphatic movement, often chosen for a lighter, de-puffed feeling.' }),
  svc({ name: 'Full Body Lymphatic Drainage', categorySlug: 'body-beauty', price: 68000, duration: 60, order: 2,
    short: 'Our lymphatic drainage technique extended across the full body.',
    description: 'The same gentle, rhythmic lymphatic drainage technique carried across the entire body for a fuller, more complete session.' }),
  svc({ name: 'Lymphatic Drainage + Steam Therapy', categorySlug: 'body-beauty', price: 80000, duration: 75, order: 3,
    short: 'Full body lymphatic drainage paired with warming steam therapy.',
    description: 'Full-body lymphatic drainage preceded by warm steam therapy, combining two techniques for a longer, more thorough soft-sculpt session.' }),
  svc({ name: 'Wood Therapy', categorySlug: 'body-beauty', price: 53000, duration: 30, order: 4,
    short: 'Contoured wooden tools used to work and sculpt targeted areas.',
    description: 'A body-contouring technique using smooth, contoured wooden tools worked over targeted areas, part of our non-invasive soft-sculpt offering.' }),
  svc({ name: 'Full Body Wood Therapy', categorySlug: 'body-beauty', price: 78000, duration: 60, order: 5,
    short: 'Wood therapy extended across the full body for a fuller contouring session.',
    description: 'Our wood-therapy technique carried across the entire body, using the same contoured wooden tools over a longer, more complete session.' }),
  svc({ name: 'Wood Therapy + Vacuum Therapy', categorySlug: 'body-beauty', price: 90000, duration: 75, order: 6,
    short: 'Wood therapy paired with vacuum therapy for a more intensive sculpt session.',
    description: 'Wood therapy combined with vacuum-cup therapy in one extended session, two non-invasive contouring techniques worked together.' }),
  svc({ name: 'EMSZero Session - 1 Area', categorySlug: 'body-beauty', price: 100000, duration: 45, order: 7, serviceType: 'contouring',
    short: 'A non-invasive muscle-stimulation session focused on one target area.',
    description: 'A non-invasive body-contouring and muscle-stimulation session using EMSZero technology, focused on a single target area. Offered as a wellness and body-sculpting service, not a medical treatment.' }),
  svc({ name: 'EMSZero Session - 2 Areas', categorySlug: 'body-beauty', price: 165000, duration: 75, order: 8, serviceType: 'contouring',
    short: 'A non-invasive muscle-stimulation session covering two target areas.',
    description: 'The same non-invasive EMSZero muscle-stimulation technology applied across two target areas in one session, for a fuller contouring routine.' }),
  svc({ name: 'EMSZero + Wood Therapy Combo', categorySlug: 'body-beauty', price: 190000, duration: 120, order: 9, serviceType: 'contouring',
    short: 'EMSZero muscle stimulation paired with wood therapy in one session.',
    description: 'A combined session pairing non-invasive EMSZero muscle stimulation with hands-on wood therapy, for guests who want both techniques in a single visit.' }),
  svc({ name: 'Snatched Waist Programme - 4 Sessions', categorySlug: 'body-beauty', price: 250000, duration: 60, order: 10, sessionCount: 4, serviceType: 'package',
    short: 'A four-session soft-sculpt programme focused on the waist and midsection.',
    description: 'A structured four-session programme combining our soft-sculpt techniques, spaced across your visits and focused on the waist and midsection. Results build gradually across the full programme.' }),
  svc({ name: 'Sculpt & Tone Package - 6 Sessions', categorySlug: 'body-beauty', price: 420000, duration: 60, order: 11, sessionCount: 6, serviceType: 'package',
    short: 'A six-session body-sculpting package combining our contouring techniques.',
    description: 'A six-session package drawing on our full range of soft-sculpt techniques, planned across multiple visits for a more complete contouring routine.' }),
  svc({ name: 'Full Body Contour Plan', categorySlug: 'body-beauty', price: 380000, duration: 90, order: 12,
    short: 'A comprehensive, full-body soft-sculpt session.',
    description: 'Our most complete single-visit contouring session, combining techniques across the full body for guests wanting a thorough soft-sculpt experience.' }),

  // K. Facial rituals — category: facials
  svc({ name: 'Express Facial', categorySlug: 'facials', price: 42000, duration: 30, order: 1,
    short: 'A quick, effective facial for a fresh-faced finish in half the time.',
    description: 'A streamlined facial covering cleanse, exfoliation and hydration, built for guests short on time but not wanting to skip skincare.' }),
  svc({ name: 'Deep Cleansing Facial', categorySlug: 'facials', price: 67000, duration: 60, order: 2,
    short: 'A thorough facial focused on clearing congestion and refining texture.',
    description: 'A full facial built around deep cleansing and extraction, suited to congested or textured skin that needs a proper reset.' }),
  svc({ name: 'Hydration Facial', categorySlug: 'facials', price: 77000, duration: 60, order: 3,
    short: 'A moisture-focused facial for skin that feels tight, dry or dull.',
    description: 'Layered hydrating actives worked into the skin during this facial, aimed at replenishing moisture and restoring a soft, dewy finish.' }),
  svc({ name: 'Hydra Jelly Facial', categorySlug: 'facials', price: 57000, duration: 60, order: 4,
    short: 'A cooling jelly-mask facial for a calm, hydrated finish.',
    description: 'A gentle facial finished with a cooling jelly mask, chosen for its soothing feel and the hydrated glow it leaves behind.' }),
  svc({ name: 'Oxygen Facial', categorySlug: 'facials', price: 62000, duration: 60, order: 5,
    short: 'An oxygenating facial designed to leave skin looking brighter and refreshed.',
    description: 'A facial that infuses the skin with an oxygenating treatment, chosen for the brighter, plumped appearance it tends to leave behind.' }),
  svc({ name: 'Soothing Mask', categorySlug: 'facials', price: 30000, duration: 30, order: 6,
    short: 'A calming mask treatment for sensitive or stressed-looking skin.',
    description: 'A short, focused mask treatment formulated to calm and soothe skin that is feeling reactive, tight or overworked.' }),

  // L. Advanced facials — category: facials
  svc({ name: 'Hydrafacial', categorySlug: 'facials', price: 122000, duration: 75, order: 7,
    short: 'Our most thorough facial, combining cleansing, extraction and hydration in one device-led treatment.',
    description: 'A multi-step advanced facial that cleanses, extracts and hydrates in sequence, using a dedicated device to reach a deeper level of clean while infusing the skin with hydrating serums.' }),
  svc({ name: 'Anti-Aging Facial', categorySlug: 'facials', price: 112000, duration: 75, order: 8,
    short: 'A facial layered with firming and renewing actives for a more youthful-looking finish.',
    description: 'An advanced facial built around firming and renewing ingredients, aimed at supporting skin’s natural elasticity and radiance over time.' }),
  svc({ name: 'Acne Treatment Facial', categorySlug: 'facials', price: 87000, duration: 75, order: 9,
    short: 'A targeted facial for congested, breakout-prone skin.',
    description: 'A facial built around clarifying and calming actives, aimed at supporting clearer-looking skin over a course of visits. Offered as a skincare treatment, not a medical or dermatological procedure.' }),
  svc({ name: 'LED Facial', categorySlug: 'facials', price: 25000, duration: 20, order: 10, isAddon: true,
    short: 'Gentle LED light therapy added to any facial.',
    description: 'An LED light therapy add-on layered onto any facial, offered as a complementary wellness step rather than a medical treatment.' }),

  // M. Nail enhancements — category: allay-nail-studio
  svc({ name: 'Acrylic & Gel Full Set', categorySlug: 'allay-nail-studio', price: 40000, duration: 120, order: 1,
    short: 'A full acrylic and gel set, shaped and finished to your preference.',
    description: 'A complete acrylic and gel enhancement set, shaped, buffed and polished to your chosen length and finish.' }),
  svc({ name: 'Short Acrylic + Basic Art', categorySlug: 'allay-nail-studio', price: 45000, duration: 120, order: 2,
    short: 'A short acrylic set finished with simple, understated nail art.',
    description: 'A neat, short acrylic set finished with a light touch of nail art, for guests who like a little detail without the drama.' }),
  svc({ name: 'Short Acrylic + Technical Art', categorySlug: 'allay-nail-studio', price: 55000, duration: 150, order: 3,
    short: 'A short acrylic set with more intricate, technical nail art.',
    description: 'A short acrylic set paired with more detailed technical nail art, for guests wanting a considered design in a manageable length.' }),
  svc({ name: 'Long Acrylic + Basic Art', categorySlug: 'allay-nail-studio', price: 55000, duration: 150, order: 4,
    short: 'A long acrylic set finished with simple, understated nail art.',
    description: 'A longer acrylic set finished with light nail art, balancing statement length with an understated design.' }),
  svc({ name: 'Long Acrylic + Technical Art', categorySlug: 'allay-nail-studio', price: 65000, duration: 180, order: 5,
    short: 'A long acrylic set with detailed, technical nail art.',
    description: 'Our longest acrylic length paired with intricate technical nail art, for guests wanting the fullest statement set.' }),
  svc({ name: 'Acrylic Overlay', categorySlug: 'allay-nail-studio', price: 25000, duration: 75, order: 6,
    short: 'A strengthening acrylic overlay on your natural nails.',
    description: 'A thin acrylic layer applied over your natural nails to add strength and a smooth, polished base.' }),
  svc({ name: 'Acrylic Toes', categorySlug: 'allay-nail-studio', price: 25000, duration: 75, order: 7,
    short: 'A full acrylic enhancement set for the toes.',
    description: 'Acrylic enhancements applied to the toenails, shaped and finished to match your preferred look.' }),
  svc({ name: 'BIAB Overlay', categorySlug: 'allay-nail-studio', price: 25000, duration: 75, order: 8,
    short: 'A Builder-in-a-Bottle overlay for a strong, natural-looking finish.',
    description: 'A BIAB gel overlay applied over your natural nails, offering added strength with a finish that stays close to your natural nail shape.' }),
  svc({ name: 'BIAB Extensions', categorySlug: 'allay-nail-studio', price: 40000, duration: 120, order: 9,
    short: 'BIAB gel extensions for added length with a natural finish.',
    description: 'Builder-in-a-Bottle gel used to extend the nail with a sturdy yet natural-looking result, shaped and finished to your preferred length.' }),
  svc({ name: 'BIAB Infill', categorySlug: 'allay-nail-studio', price: 20000, duration: 75, order: 10,
    short: 'A maintenance infill to keep your BIAB set looking freshly done.',
    description: 'A maintenance visit that fills regrowth and refreshes the finish on an existing BIAB set, keeping it looking newly applied.' }),
  svc({ name: 'French Acrylic', categorySlug: 'allay-nail-studio', price: 50000, duration: 150, order: 11,
    short: 'A classic French tip finish on a fresh acrylic set.',
    description: 'A timeless French-tip finish applied over a fresh acrylic set, clean lines and a polished, classic result.' }),
  svc({ name: 'Chrome Finish', categorySlug: 'allay-nail-studio', price: 15000, duration: 30, order: 12, isAddon: true,
    short: 'A reflective chrome powder finish over your existing set.',
    description: 'A mirror-like chrome powder finish applied over an existing set, for a striking, reflective final look.' }),
  svc({ name: 'Ombre Nails - 2 Colors', categorySlug: 'allay-nail-studio', price: 20000, duration: 45, order: 13, isAddon: true,
    short: 'A soft, blended ombré finish in two colours of your choice.',
    description: 'A smoothly blended two-tone ombré finish, colours chosen and layered for a soft gradient effect.' }),
  svc({ name: 'Wedding Nails - Custom', categorySlug: 'allay-nail-studio', price: 80000, duration: 180, order: 14, serviceType: 'premium',
    short: 'A fully custom nail design created for your wedding day.',
    description: 'A bespoke nail design planned around your wedding look, from colour palette to fine detail, finished for a day that calls for extra care.' }),
  svc({ name: 'Nail Wraps', categorySlug: 'allay-nail-studio', price: 12000, duration: 45, order: 15,
    short: 'Pre-designed nail wraps applied for a quick, precise finish.',
    description: 'Nail wraps applied and finished for a precise, even design without the longer sitting time of hand-painted art.' }),
  svc({ name: 'Stick-On Nails', categorySlug: 'allay-nail-studio', price: 8000, duration: 30, order: 16,
    short: 'A quick, damage-free stick-on nail application.',
    description: 'Press-on nails fitted and applied for an instant, low-commitment finish, ideal for a quick refresh before an event.' }),

  // N. Nail care — category: allay-nail-studio
  svc({ name: 'Gel Polish - Hands', categorySlug: 'allay-nail-studio', price: 10000, duration: 45, order: 17,
    short: 'A long-wearing gel polish application for the hands.',
    description: 'A clean gel polish application on natural nails, chip-resistant and finished with a glossy topcoat.' }),
  svc({ name: 'Gel Polish - Toes', categorySlug: 'allay-nail-studio', price: 10000, duration: 45, order: 18,
    short: 'A long-wearing gel polish application for the toes.',
    description: 'A neat gel polish application on the toenails, finished with a durable, glossy topcoat.' }),
  svc({ name: 'Manicure', categorySlug: 'allay-nail-studio', price: 18000, duration: 60, order: 19,
    short: 'A classic manicure covering shape, cuticle care and polish.',
    description: 'A full manicure including shaping, cuticle care, hand massage and polish, a considered reset for hands that need it.' }),
  svc({ name: 'Pedicure', categorySlug: 'allay-nail-studio', price: 35000, duration: 75, order: 20,
    short: 'A full pedicure with soak, exfoliation and polish.',
    description: 'A complete pedicure covering a warm soak, exfoliation, shaping and polish, finished with a foot massage for a fuller sense of care.' }),
  svc({ name: 'Extra Design - Per Finger', categorySlug: 'allay-nail-studio', price: 2500, priceUnitLabel: 'per finger', duration: 10, order: 21, isAddon: true,
    short: 'An additional design detail, priced per finger.',
    description: 'A single extra design detail added to any nail service, priced per finger for guests wanting just a few accent nails.' }),
  svc({ name: 'Stones - Per Finger', categorySlug: 'allay-nail-studio', price: 2500, priceUnitLabel: 'per finger', duration: 10, order: 22, isAddon: true,
    short: 'Decorative stone detailing, priced per finger.',
    description: 'Small decorative stones applied as an accent to your nail set, priced per finger for as much or as little sparkle as you like.' }),
  svc({ name: 'Soak Off', categorySlug: 'allay-nail-studio', price: 4000, duration: 30, order: 23, isAddon: true,
    short: 'Safe, gentle removal of a previous gel or acrylic set.',
    description: 'A careful soak-off removal of an existing gel, acrylic or BIAB set, done gently to protect the natural nail underneath.' }),
  svc({ name: 'Repair - Per Finger', categorySlug: 'allay-nail-studio', price: 4000, priceUnitLabel: 'per finger', duration: 15, order: 24, isAddon: true,
    short: 'A quick repair for a chipped or broken nail, priced per finger.',
    description: 'A targeted repair for a single chipped, cracked or lifted nail, priced per finger to keep your set looking complete between full visits.' }),

  // O. Lashes — category: allay-lash-studio
  svc({ name: 'Classic Lash Set', categorySlug: 'allay-lash-studio', price: 30000, duration: 120, order: 1,
    short: 'A natural, one-to-one classic lash extension set.',
    description: 'Individual extensions applied one to one on your natural lashes, for a soft, natural enhancement that still looks like your own lashes, just fuller.' }),
  svc({ name: 'Hybrid Lash Set', categorySlug: 'allay-lash-studio', price: 40000, duration: 150, order: 2,
    short: 'A mix of classic and volume lashes for texture without full drama.',
    description: 'A blend of classic and volume lash techniques, giving added texture and definition while staying softer than a full volume set.' }),
  svc({ name: 'Volume Lash Set', categorySlug: 'allay-lash-studio', price: 50000, duration: 150, order: 3,
    short: 'A fuller, more dramatic lash set using multiple fine extensions per lash.',
    description: 'Lightweight fans of fine extensions applied to each natural lash for noticeably fuller volume, without adding unnecessary weight.' }),
  svc({ name: 'Wispy / Wet Look Lashes', categorySlug: 'allay-lash-studio', price: 55000, duration: 150, order: 4,
    short: 'A textured, spiked lash set for a wispy, wet-look finish.',
    description: 'A deliberately textured lash set mixing lengths for a wispy, spiked effect, popular for its soft-edged, natural-but-defined finish.' }),
  svc({ name: 'Mega Volume Lashes', categorySlug: 'allay-lash-studio', price: 70000, duration: 180, order: 5,
    short: 'Our most dramatic lash set, built with ultra-fine extension fans.',
    description: 'The fullest lash set we offer, using very fine extensions layered into dense fans for maximum volume and drama.' }),

  // P. Lash maintenance — category: allay-lash-studio
  svc({ name: 'Lash Refill', categorySlug: 'allay-lash-studio', price: 18000, priceFrom: 18000, priceIsFrom: true, duration: 90, order: 6,
    short: 'A refill to keep an existing lash set looking full, from ₦18,000.',
    description: 'A maintenance visit that replaces grown-out extensions and restores fullness to an existing set. Final price depends on how much regrowth needs filling and the original set style.' }),
  svc({ name: 'Lash Removal', categorySlug: 'allay-lash-studio', price: 9000, duration: 30, order: 7,
    short: 'Safe, gentle removal of existing lash extensions.',
    description: 'A careful removal of existing lash extensions using a gentle solution designed to protect your natural lashes underneath.' }),
  svc({ name: 'Lash Bath', categorySlug: 'allay-lash-studio', price: 6000, duration: 20, order: 8,
    short: 'A deep cleanse for lash extensions to keep them fresh between fills.',
    description: 'A thorough cleanse of existing lash extensions to remove build-up and refresh their appearance between full refill visits.' }),

  // Q. Brows — category: allay-lash-studio
  svc({ name: 'Brow Shaping', categorySlug: 'allay-lash-studio', price: 9000, duration: 30, order: 9,
    short: 'Precise brow shaping to suit your natural brow line.',
    description: 'Careful shaping to clean up and define your natural brow line, tailored to the shape that suits your face.' }),
  svc({ name: 'Brow Tint', categorySlug: 'allay-lash-studio', price: 13000, duration: 30, order: 10,
    short: 'A brow tint for fuller-looking definition.',
    description: 'A semi-permanent tint applied to the brows for richer colour and more visible definition between shaping visits.' }),
  svc({ name: 'Brow Lamination', categorySlug: 'allay-lash-studio', price: 28000, duration: 60, order: 11,
    short: 'A lamination treatment that sets brow hairs into a fuller, uniform shape.',
    description: 'A lamination treatment that softens and resets brow hairs into a smoother, more uniform shape, giving a fuller, brushed-up finish that holds for weeks.' }),
  svc({ name: 'Brow Tint + Lamination', categorySlug: 'allay-lash-studio', price: 40000, duration: 75, order: 12,
    short: 'Brow lamination and tint together for full, defined brows.',
    description: 'Our brow lamination treatment paired with a tint, combining shape, hold and colour for the fullest possible brow finish in one visit.' }),

  // R. Waxing — category: waxing
  svc({ name: 'Chin Wax', categorySlug: 'waxing', price: 8500, duration: 15, order: 1,
    short: 'A quick, precise wax for the chin area.',
    description: 'A fast, precise waxing service for the chin, done with care for sensitive skin.' }),
  svc({ name: 'Upper Lip Wax', categorySlug: 'waxing', price: 6500, duration: 15, order: 2,
    short: 'A quick, precise wax for the upper lip.',
    description: 'A fast, gentle waxing service for the upper lip area, finished with a smoothing balm.' }),
  svc({ name: 'Eyebrow Wax', categorySlug: 'waxing', price: 6500, duration: 20, order: 3,
    short: 'Clean brow shaping using wax.',
    description: 'Precise wax-based shaping to clean up and define the brow line.' }),
  svc({ name: 'Underarm Wax', categorySlug: 'waxing', price: 13500, duration: 20, order: 4,
    short: 'A thorough underarm wax for smooth, long-lasting results.',
    description: 'A full underarm waxing service, done efficiently and with care for sensitive skin in this area.' }),
  svc({ name: 'Half Arm Wax', categorySlug: 'waxing', price: 11500, duration: 30, order: 5,
    short: 'Waxing from elbow to wrist, or shoulder to elbow.',
    description: 'A half-arm waxing service covering either the upper or lower arm, for smooth, hair-free skin.' }),
  svc({ name: 'Full Arm Wax', categorySlug: 'waxing', price: 19000, duration: 45, order: 6,
    short: 'Full-arm waxing from shoulder to wrist.',
    description: 'A complete full-arm waxing service from shoulder to wrist, for thoroughly smooth results.' }),
  svc({ name: 'Half Leg Wax', categorySlug: 'waxing', price: 19000, duration: 45, order: 7,
    short: 'Waxing from knee to ankle, or thigh to knee.',
    description: 'A half-leg waxing service covering either the upper or lower leg, quick and thorough.' }),
  svc({ name: 'Full Leg Wax', categorySlug: 'waxing', price: 26000, duration: 60, order: 8,
    short: 'Full-leg waxing from thigh to ankle.',
    description: 'A complete full-leg waxing service, from thigh to ankle, for smooth, even results.' }),
  svc({ name: 'Brazilian Wax', categorySlug: 'waxing', price: 26000, duration: 45, order: 9,
    short: 'A thorough Brazilian wax performed with care and discretion.',
    description: 'A full Brazilian waxing service performed with care, discretion and attention to comfort throughout.' }),
  svc({ name: 'Back Wax', categorySlug: 'waxing', price: 40000, duration: 60, order: 10,
    short: 'A full back wax for smooth, hair-free skin.',
    description: 'A thorough waxing service covering the full back, done efficiently for even, lasting results.' }),
  svc({ name: 'Full Body Wax', categorySlug: 'waxing', price: 97000, duration: 120, order: 11,
    short: 'A complete full-body waxing service in a single visit.',
    description: 'Our most complete waxing service, covering the full body in one extended visit for guests wanting everything done at once.' }),

  // S. Pilates studio — category: allay-pilates
  svc({ name: 'Single Reformer Class', categorySlug: 'allay-pilates', price: 22000, duration: 50, order: 1,
    short: 'A single reformer Pilates class, drop-in style.',
    description: 'One reformer Pilates class, no commitment required, for guests wanting to try a session or top up between packages.' }),
  svc({ name: 'Private Pilates Session', categorySlug: 'allay-pilates', price: 53000, duration: 50, order: 2,
    short: 'A one-on-one Pilates session tailored entirely to you.',
    description: 'A private, one-on-one Pilates session with full instructor attention, paced and adapted to your goals and experience level.' }),
  svc({ name: 'Group Pilates Class', categorySlug: 'allay-pilates', price: 16000, duration: 50, order: 3,
    short: 'A small-group Pilates class for shared motivation and energy.',
    description: 'A guided small-group Pilates class combining structured movement with the energy of training alongside others.' }),
  svc({ name: 'Reformer Pilates - 4 Classes Monthly', categorySlug: 'allay-pilates', price: 85000, duration: 50, order: 4, sessionCount: 4, serviceType: 'package',
    short: 'Four reformer Pilates classes each month, at a package rate.',
    description: 'A monthly package of four reformer Pilates classes, a steady rhythm for guests building a regular movement practice.' }),
  svc({ name: 'Reformer Pilates - 8 Classes Monthly', categorySlug: 'allay-pilates', price: 160000, duration: 50, order: 5, sessionCount: 8, serviceType: 'package',
    short: 'Eight reformer Pilates classes each month, up to twice weekly.',
    description: 'A monthly package of eight reformer Pilates classes, roughly twice a week, for guests wanting consistent, frequent practice.' }),
  svc({ name: 'Reformer Pilates - Unlimited Monthly', categorySlug: 'allay-pilates', price: 320000, duration: 50, order: 6, serviceType: 'package',
    short: 'Unlimited reformer Pilates classes for the month.',
    description: 'Unlimited access to reformer Pilates classes for a full month, for guests who want to train as often as they like.' }),

  // T. Signature experiences — category: signature-experiences
  svc({ name: 'Allay House Full Day Reset', categorySlug: 'signature-experiences', price: 250000, duration: 360, order: 1, serviceType: 'signature',
    short: 'A full day at Allay House: head spa, massage, hammam, pedicure, refreshments and a Pilates class.',
    description: 'A complete day built around our signature rituals, head spa, massage, hammam, pedicure, a Pilates class and refreshments throughout, spaced across the day so nothing feels rushed. Our most complete single-visit experience.' }),
  svc({ name: 'Bridal Glow Experience', categorySlug: 'signature-experiences', price: 320000, duration: 300, order: 2, serviceType: 'signature',
    short: 'A bridal-day ritual covering skin, body and hair preparation, massage, lashes, manicure and pedicure.',
    description: 'A considered bridal preparation sequence, skin and body preparation, hair preparation, massage, lashes, manicure and pedicure, timed to leave you calm, glowing and ready. Planned around your wedding-day schedule at consultation.' }),
  svc({ name: 'Corporate Wellness Retreat', categorySlug: 'signature-experiences', price: 150000, priceUnitLabel: 'per person', duration: 180, order: 3, serviceType: 'signature',
    short: 'A wellness retreat for teams, priced per person, with a wellness talk, Pilates, massage and refreshments.',
    description: 'A team wellness experience combining a guided wellness talk, a Pilates class, massage and refreshments, priced per person and planned around your group’s size and schedule. A considered way to bring wellness into a corporate calendar.' }),
]

export const memberships = [
  {
    name: 'The Reset',
    slug: 'the-reset',
    tagline: 'A monthly wellness reset.',
    monthlyPrice: 250000,
    displayOrder: 1,
    isFeatured: false,
    description: 'An entry-level monthly Allay House membership designed for guests who want a balanced routine of beauty, hair, relaxation and Pilates experiences throughout the month.',
    terms: 'Benefits reset each month and do not roll over. Massage and Pilates class allocations are subject to availability. Membership can be paused or cancelled with notice consistent with Allay House policy at the time.',
    benefits: [
      '1 Signature Japanese Head Spa',
      '1 Natural Hair Treatment',
      '1 Cornrow Styling',
      '1 Swedish Massage',
      '1 Traditional Hammam Ritual',
      '2 Reformer Pilates Classes',
      '1 Jelly Pedicure',
      'Healthy refreshments during every visit',
      'Priority booking',
      '10% off additional services',
      'Birthday Wellness Day Treat',
    ],
  },
  {
    name: 'The Ritual',
    slug: 'the-ritual',
    tagline: 'Wellness. Beauty. Balance.',
    monthlyPrice: 480000,
    displayOrder: 2,
    isFeatured: true,
    description: 'A premium monthly membership combining regular beauty treatments, wellness rituals, massage, Pilates access and elevated booking benefits.',
    terms: 'Eligible massage choices are Swedish, Deep Tissue or Aromatherapy. Reformer Pilates classes are available up to twice weekly. Benefits reset each month and do not roll over. Membership can be paused or cancelled with notice consistent with Allay House policy at the time.',
    benefits: [
      '2 Signature Head Spa Treatments',
      '2 Natural Hair Treatments',
      '2 Cornrow Styling Sessions',
      '2 Premium Massages (Swedish, Deep Tissue or Aromatherapy)',
      '1 Deluxe Hammam Ritual',
      '8 Reformer Pilates Classes (up to twice weekly)',
      '2 Jelly Pedicures',
      'Unlimited healthy refreshments',
      'Steam room access on every visit',
      '15% off additional services',
      'Priority weekend booking',
      '1 complimentary Pilates guest pass every month',
      'Birthday Wellness Day Treat',
    ],
  },
  {
    name: 'The Sanctuary',
    slug: 'the-sanctuary',
    tagline: 'The ultimate Allay House lifestyle.',
    monthlyPrice: 850000,
    displayOrder: 3,
    isFeatured: false,
    description: 'The highest Allay House membership tier, created for guests who want frequent treatments, unlimited reformer Pilates, premium priority access and exclusive guest benefits.',
    terms: 'Unlimited Reformer Pilates classes are subject to studio capacity. The monthly guest benefit applies to one eligible shared service (Head Spa, Massage, Pilates, Hammam or Pedicure) per month, alongside two complimentary Pilates guest passes. Benefits reset each month and do not roll over. Membership can be paused or cancelled with notice consistent with Allay House policy at the time.',
    benefits: [
      '4 Signature Head Spa Treatments',
      '4 Natural Hair Treatments',
      '4 Cornrow Styling Sessions',
      '4 Premium Massages',
      '1 Luxury Hammam Experience',
      'Unlimited Reformer Pilates Classes',
      '2 Jelly Pedicures',
      'Unlimited healthy refreshments',
      '20% off all additional services',
      'VIP priority booking',
      'Complimentary steam room access',
      'Complimentary wellness consultation',
      'Birthday Wellness Day Treat',
      'Share the Sanctuary: once a month, invite one guest to enjoy one complimentary eligible service with you (Head Spa, Massage, Pilates, Hammam or Pedicure)',
      '2 complimentary Pilates guest passes every month',
    ],
  },
]

// Shared perks displayed alongside all membership plans (identical for every
// plan, so kept as static content rather than duplicated per-row in the DB).
export const sharedMemberPerks = [
  'Dedicated members’ booking line',
  'Priority waitlist for fully booked days',
  'Complimentary Wi-Fi',
  'Refreshments during every visit',
  'Member-only pricing on retail products',
  'Exclusive invitations to wellness events',
  'Early access to new treatments',
  'Flexible appointment rescheduling',
]
