export const imagePaths = {
  brand: {
    logoBrown: '/images/brand/allay-logo-brown.svg',
    logoWhite: '/images/brand/allay-logo-white.svg',
    logoDark: '/images/brand/allay-logo-white.svg',
    logoLight: '/images/brand/allay-logo-brown.svg',
    mark: '/images/allay/brand/allay-mark.png',
    favicon: '/images/allay/brand/favicon.svg',
  },
  home: {
    heroMain: '/images/allay/home/home-hero-main.jpg',
    heroSecondary: '/images/allay/home/home-hero-main.png',
    heroDetail: '/images/allay/home/home-wellness-section.jpg',
    texture: '/images/allay/home/home-texture.png',
    wellnessSection: '/images/allay/home/home-wellness-section.jpg',
    wellnessSectionWide: '/images/allay/home/home-wellness-section.png',
    experienceSection: '/images/allay/home/home-wellness-section.jpg',
  },
  categories: {
    allServices: '/images/allay/categories/all-services.jpg',
    spa: '/images/allay/categories/category-spa.png',
    pilates: '/images/allay/categories/category-pilates.png',
    nailStudio: '/images/allay/categories/category-nail-studio.png',
    lashStudio: '/images/allay/categories/allay-lash-studio.png',
    salon: '/images/allay/categories/category-salon.png',
    facials: '/images/allay/categories/category-facials.png',
    massage: '/images/allay/categories/category-massage.png',
    sauna: '/images/allay/categories/sauna.png',
    headspa: '/images/allay/categories/category-headspa.png',
    hairBraiding: '/images/allay/categories/category-wigs.png',
    wigs: '/images/allay/categories/category-wigs.png',
    bodyBeauty: '/images/allay/categories/body-and-beauty.png',
    advancedSkinTreatment: '/images/allay/categories/advanced-skin-treatment.png',
  },
  about: {
    hero: '/images/allay/about/about-hero.jpg',
    interior: '/images/allay/about/about-interior.png',
    care: '/images/allay/about/about-interior.png',
    brandStory: '/images/allay/about/about-hero.png',
  },
  contact: {
    hero: '/images/allay/contact/contact-hero.jpg',
    location: '/images/allay/contact/contact-hero.png',
    interior: '/images/allay/contact/contact-interior.png',
  },
  auth: {
    signin: '/images/allay-house-hero.png',
    signup: '/images/allay-house-hero.png',
    adminLoginBg: '/images/allay-house-hero.png',
    side: '/images/allay-house-hero.png',
  },
  waitlist: {
    hero: '/images/allay-house-hero.png',
    side: '/images/allay-house-hero.png',
    success: '/images/allay-house-hero.png',
  },
  booking: {
    hero: '/images/allay-house-hero.png',
    side: '/images/allay-house-hero.png',
    success: '/images/allay-house-hero.png',
    empty: '/images/allay-house-hero.png',
  },
  services: {
    swedishMassage: '',
    deepTissueMassage: '',
    aromatherapyMassage: '',
    classicFacial: '',
    hydratingFacial: '',
    glowFacial: '',
    saunaSession: '',
    headspaTreatment: '',
    classicManicure: '',
    classicPedicure: '',
    gelPolish: '',
    nailArt: '',
    lashExtensions: '',
    lashLift: '',
    browShaping: '',
    hairStyling: '',
    hairBraiding: '',
    wigInstallation: '',
    wigStyling: '',
    privatePilates: '',
    groupPilates: '',
  },
  placeholders: {
    hero: '/images/allay-house-hero.png',
    category: '/images/allay/categories/all-services.jpg',
    service: '',
    avatar: '',
    empty: '',
    logo: '',
  },
}

export default imagePaths
