export const imagePaths = {
  brand: {
    logoDark: '/images/allay/brand/allay-logo-dark.png',
    logoLight: '/images/allay/brand/allay-logo-light.png',
    mark: '/images/allay/brand/allay-mark.png',
    favicon: '/images/allay/brand/favicon.png',
  },
  home: {
    heroMain: '/images/allay/home/home-hero-main.png',
    heroSecondary: '/images/allay/home/home-hero-secondary.png',
    heroDetail: '/images/allay/home/home-hero-detail.png',
    texture: '/images/allay/home/home-texture.png',
    wellnessSection: '/images/allay/home/home-wellness-section.png',
    experienceSection: '/images/allay/home/home-experience-section.png',
  },
  categories: {
    spa: '/images/allay/categories/category-spa.png',
    pilates: '/images/allay/categories/category-pilates.png',
    nailStudio: '/images/allay/categories/category-nail-studio.png',
    lashStudio: '/images/allay/categories/allay-lash-studio.png',
    salon: '/images/allay/categories/category-salon.png',
    facials: '/images/allay/categories/category-facials.png',
    massage: '/images/allay/categories/category-massage.png',
    sauna: '/images/allay/categories/sauna.png',
    headspa: '/images/allay/categories/category-headspa.png',
    hairBraiding: '/images/allay/categories/category-hair-braiding.png',
    wigs: '/images/allay/categories/category-wigs.png',
    bodyBeauty: '/images/allay/categories/body-and-beauty.png',
    advancedSkinTreatment: '/images/allay/categories/advanced-skin-treatment.png',
  },
  about: {
    hero: '/images/allay/about/about-hero.png',
    interior: '/images/allay/about/about-interior.jpg',
    care: '/images/allay/about/about-care.jpg',
    brandStory: '/images/allay/about/about-brand-story.jpg',
  },
  contact: {
    hero: '/images/allay/contact/contact-hero.png',
    location: '/images/allay/contact/contact-location.jpg',
    interior: '/images/allay/contact/contact-interior.png',
  },
  auth: {
    signin: '/images/allay/auth/auth-signin.jpg',
    signup: '/images/allay/auth/auth-signup.jpg',
    adminLoginBg: '/images/allay/auth/admin-login-bg.jpg',
    side: '/images/allay/auth/auth-side.jpg',
  },
  waitlist: {
    hero: '/images/allay/waitlist/waitlist-hero.jpg',
    side: '/images/allay/waitlist/waitlist-side.jpg',
    success: '/images/allay/waitlist/waitlist-success.jpg',
  },
  booking: {
    hero: '/images/allay/booking/booking-hero.jpg',
    side: '/images/allay/booking/booking-side.jpg',
    success: '/images/allay/booking/booking-success.jpg',
    empty: '/images/allay/booking/booking-empty.jpg',
  },
  services: {
    swedishMassage: '/images/allay/services/service-swedish-massage.jpg',
    deepTissueMassage: '/images/allay/services/service-deep-tissue-massage.jpg',
    aromatherapyMassage: '/images/allay/services/service-aromatherapy-massage.jpg',
    classicFacial: '/images/allay/services/service-classic-facial.jpg',
    hydratingFacial: '/images/allay/services/service-hydrating-facial.jpg',
    glowFacial: '/images/allay/services/service-glow-facial.jpg',
    saunaSession: '/images/allay/services/service-sauna-session.jpg',
    headspaTreatment: '/images/allay/services/service-headspa-treatment.jpg',
    classicManicure: '/images/allay/services/service-classic-manicure.jpg',
    classicPedicure: '/images/allay/services/service-classic-pedicure.jpg',
    gelPolish: '/images/allay/services/service-gel-polish.jpg',
    nailArt: '/images/allay/services/service-nail-art.jpg',
    lashExtensions: '/images/allay/services/service-lash-extensions.jpg',
    lashLift: '/images/allay/services/service-lash-lift.jpg',
    browShaping: '/images/allay/services/service-brow-shaping.jpg',
    hairStyling: '/images/allay/services/service-hair-styling.jpg',
    hairBraiding: '/images/allay/services/service-hair-braiding.jpg',
    wigInstallation: '/images/allay/services/service-wig-installation.jpg',
    wigStyling: '/images/allay/services/service-wig-styling.jpg',
    privatePilates: '/images/allay/services/service-private-pilates.jpg',
    groupPilates: '/images/allay/services/service-group-pilates.jpg',
  },
  placeholders: {
    hero: '/images/allay/placeholders/placeholder-hero.jpg',
    category: '/images/allay/placeholders/placeholder-category.jpg',
    service: '/images/allay/placeholders/placeholder-service.jpg',
    avatar: '/images/allay/placeholders/placeholder-avatar.jpg',
    empty: '/images/allay/placeholders/placeholder-empty.jpg',
    logo: '/images/allay/placeholders/placeholder-logo.png',
  },
}

export default imagePaths
