export const imagePaths = {
  brand: {
    logoBrown: '/images/brand/allay-logo-brown.svg',
    logoWhite: '/images/brand/allay-logo-white.svg',
    logoDark: '/images/brand/allay-logo-white.svg',
    logoLight: '/images/brand/allay-logo-brown.svg',
    mark: '/images/brand/allay-logo-brown.svg',
    favicon: '/images/brand/favicon.svg',
  },
  home: {
    heroMain: '/images/allay/home/home-hero-main-portrait.webp',
    heroSecondary: '/images/allay/home/home-hero-main.webp',
    heroDetail: '/images/allay/home/home-wellness-section-portrait.webp',
    texture: '/images/allay/home/home-texture.webp',
    wellnessSection: '/images/allay/home/home-wellness-section-portrait.webp',
    wellnessSectionWide: '/images/allay/home/home-wellness-section.webp',
    experienceSection: '/images/allay/home/home-wellness-section-portrait.webp',
  },
  categories: {
    allServices: '/images/allay/categories/all-services.webp',
    spa: '/images/allay/categories/category-spa.webp',
    pilates: '/images/allay/categories/category-pilates.webp',
    nailStudio: '/images/allay/categories/category-nail-studio.webp',
    salon: '/images/allay/categories/category-salon.webp',
    facials: '/images/allay/categories/category-facials.webp',
    massage: '/images/allay/categories/category-massage.webp',
    sauna: '/images/allay/categories/sauna.webp',
    headspa: '/images/allay/categories/category-headspa.webp',
    hairBraiding: '/images/allay/categories/category-wigs.webp',
    wigs: '/images/allay/categories/category-wigs.webp',
    bodyBeauty: '/images/allay/categories/body-and-beauty.webp',
    advancedSkinTreatment: '/images/allay/categories/advanced-skin-treatment.webp',
  },
  about: {
    hero: '/images/allay/about/about-hero-portrait.webp',
    interior: '/images/allay/about/about-interior.webp',
    care: '/images/allay/about/about-interior.webp',
    brandStory: '/images/allay/about/about-hero.webp',
  },
  contact: {
    hero: '/images/allay/contact/contact-hero-portrait.webp',
    location: '/images/allay/contact/contact-hero.webp',
    interior: '/images/allay/contact/contact-hero.webp',
  },
  auth: {
    signin: '/images/allay-house-hero.webp',
    signup: '/images/allay-house-hero.webp',
    adminLoginBg: '/images/allay-house-hero.webp',
    side: '/images/allay-house-hero.webp',
  },
  waitlist: {
    hero: '/images/allay-house-hero.webp',
    side: '/images/allay-house-hero.webp',
    success: '/images/allay-house-hero.webp',
  },
  booking: {
    hero: '/images/allay-house-hero.webp',
    side: '/images/allay-house-hero.webp',
    success: '/images/allay-house-hero.webp',
    empty: '/images/allay-house-hero.webp',
  },
  placeholders: {
    hero: '/images/allay-house-hero.webp',
    category: '/images/allay/categories/all-services.webp',
    service: '',
    avatar: '',
    empty: '',
    logo: '',
  },
}

export default imagePaths
